@startuml
'https://plantuml.com/class-diagram

class NewEmployee {
    - lastName
    - firstName
    - salary
    + lineSave()
    + goThroughLast()
    + goThroughFirst()
    + goThroughSal()

}

class PrintThings()
{
    + printHeader()
    + printRecords()
}


@enduml